# Generated by Django 5.0 on 2024-06-06 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bezaklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('soni', models.IntegerField()),
                ('umumiynarx', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bezaklarcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulotcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('long', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('umumiynarx', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matocategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bezakkirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField(default=0)),
                ('narxi', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('umumiynarx', models.CharField(max_length=100)),
                ('bezak_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bezaklar')),
            ],
        ),
        migrations.AddField(
            model_name='bezaklar',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bezaklarcategory'),
        ),
        migrations.CreateModel(
            name='Mahsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.mahsulotcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Bezakchiqm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('soni', models.IntegerField(default=0)),
                ('bezak_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bezaklar')),
                ('mahsulot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.mahsulotlar')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulotkirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField(default=0)),
                ('bezaklar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bezaklar')),
                ('mahsulot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.mahsulotlar')),
                ('mato_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.mato')),
            ],
        ),
        migrations.AddField(
            model_name='mato',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.matocategory'),
        ),
        migrations.CreateModel(
            name='Matochiqim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('soni', models.IntegerField(default=0)),
                ('mahsulot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.mahsulotlar')),
                ('mato_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.mato')),
            ],
        ),
        migrations.CreateModel(
            name='Matokrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField(default=0)),
                ('narxi', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('umumiynarx', models.CharField(max_length=100)),
                ('mato_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.mato')),
            ],
        ),
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField(default=0)),
                ('narxi', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mahsulot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.mahsulotlar')),
            ],
        ),
    ]
