# Generated by Django 5.0 on 2024-06-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bezaklar',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
