# Generated by Django 5.0 on 2024-06-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_bezaklar_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accaount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=300)),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='bezakchiqm',
            name='date',
        ),
    ]
